name: DAG_IOUv2
params:
  - lower_bound: 0.005 #x10
    upper_bound: 0.01
    p: 100
    iou_type: "iou"
  - lower_bound: 0.06 #x20
    upper_bound: 0.12
    iou_type: "iou"
  - lower_bound: 3.0 #x50
    upper_bound: 6.0
    iou_type: "iou"
