defaults:
  - _self_
  - dataset: mot_noise
  - dataset@gt_dataset: mot
  - algo: tdtr_iou
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

# Directories for data
interim: ./interim
output: ./output
